// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const root: string;
export const at: string;
export const separator: string;
export const name: string;
