// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const root: string;
export const company: string;
export const dateRange: string;
export const desc: string;
export const projects: string;
export const project: string;
export const flexWrapper: string;
export const figure: string;
export const skillSetsVis: string;
export const skills: string;
