// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const root: string;
export const tip: string;
export const fig: string;
export const inner: string;
