// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const root: string
export const rating: string
export const nameLink: string
export const ratings: string
export const strengthRating: string
export const stale: string
