// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const root: string
export const dim: string
export const ghLink: string
export const resumeLink: string
