// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const root: string;
export const contact: string;
export const rowOne: string;
export const rowTwo: string;
export const objective: string;
export const actions: string;
export const shadow: string;
